services:
  - type: web
    name: sleep-disorder-app
    env: python
    buildCommand: cd FRONTEND && pip install -r ../requirements.txt
    startCommand: gunicorn self.wsgi:application
    workingDir: FRONTEND
    envVars:
      - key: DJANGO_SECRET_KEY
        value: _4_kzz_xi9c2mg&5&mrs#rv-#)4ho+kq58ebm3+(_7g)02o9qd
      - key: DEBUG
        value: False
