# Exported from Render on 2025-07-14T16:41:52Z
services:
- type: web
  name: Sleep-Disorder-Detection
  runtime: python
  repo: https://github.com/mohan-krishna-reddy28/Sleep_Disorder
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn self.wsgi:application
  autoDeployTrigger: commit
  rootDir: FRONTEND
version: "1"
